[book]
title = "Aeon Docs"
authors = ["Max Waine"]
description = "Documentation for Aeon."
language = "en"
src = "md"

[output.html]
theme = "theme"
additional-css = [
	"css/elements.css",
	"css/hljs.css",
	"css/restyle.css",
]
no-section-label = true
git-repository-url = "https://github.com/Altazimuth/aeon-docs"
site-url = "https://mwaine.com/aeon-docs/"

[output.html.fold]
enable = true

[preprocessor.aeon-doc]
command = "ruby tools/preproc.rb"
renderer = ["html"]
